version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: '${MONGO_DB:-dns-lookup}' 
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME:-dnsuser}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD:-dnspass}'
      MONGO_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init-mongo.sh
    volumes:
      - ./mongodb:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    

  dns-lookup-app:
    build: .
    container_name: dns-lookup-app
    restart: always
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME:-dnsuser}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-dnspass}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/}
      MONGO_DB: ${MONGO_DB:-dns-lookup}
      PORT: ${DNS_LOOKUP_APP:-80}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo
    
